title: Schulte development
author: Markus Schulte
email: mail@schulte-development.de
avatar: assets/img/markus-schulte.jpg
url: https://schulte-development.de
keywords: "Azure,AWS,technical architect,Java,Golang"
plugins:
  - jekyll-remote-theme
remote_theme: daattali/beautiful-jekyll
navbar-links:
  About Me: "/#about-me"
  Services: "/#my-services"
  Portfolio: "/#my-portfolio"
  Imprint: imprint
social-network-links:
  email: mail@schulte-development.de
  linkedin: markus-schulte
  github: SchulteMarkus
  stackoverflow: markus-schulte
footer-extra: footer-navigation.html

