title: Schulte development
author: Markus Schulte
email: mail@schulte-development.de
avatar: assets/markus-schulte.jpg
url: https://schulte-development.de
remote_theme: daattali/beautiful-jekyll
plugins:
  - jekyll-remote-theme
edit_page_button: true
navbar-links:
  Imprint: imprint
social-network-links:
  email: mail@schulte-development.de
  linkedin: markus-schulte
  github: SchulteMarkus
  stackoverflow: markus-schulte
footer-extra: footer-navigation.html

