- title: Technical cloud architect
  description: >
    As a technical cloud architect, I design IT systems and support the implementing team of 
    specialists in realizing them
  skills: Cloud, design
- title: Programming
  description: >
    I have a lot of experience as an engineer, usually working with Java or Golang and some 
    TypeScript in the last years.
  skills: Clean code, Java, Golang, Git, Build tools
- title: DevOp
  description: >
    In addition to designing and implementing software, I am also proficient in continuous 
    integration and operation
  skills: DevOps, CI/CD, Monitoring
- title: Leadership
  description: >
    I can lead a team of specialists to the goal and, in addition to mentoring, also set the 
    direction internally and carry out stakeholder management externally
  skills: Strategic thinking, Communication, Decision-making, Mentorship, Stakeholder management
